### ISSUE TITLE
I'd like to ask your opinion on atomic design patterns and tests!

### ISSUE THREAD

**Issue by zestlee1106** [florianldt/tkcreativekit#3]
Hello, 
I heard your last presentation well. Thank you.

There are a few things I would like to ask for your opinion.

1. How can I create a directory structure with atomic design patterns applied?
- Inside the current tkcreativekit's src, there is each component directory
- I want to divide the atomic pattern structure into directories. (`/src/components/atoms`, `/src/components/molecules` ... etc)
2. Do you think storybook, jest, and cypress should all be introduced in each component to create a test-friendly project?
- So, I think there's going to be a `Badge.stories.tsx`, `Badge.tsx`, `index.ts`, `style.ts`, `types.ts`, `Badge.spec.ts`, `Badge.cy.ts` file under the `/src/badge/` directory.
- I think the maintenance points will increase too much, what do you think?

**Comment by florianldt** [comment]
Hi and thank you for the feedback.

Regarding your questions:

1. As said during the talk, I am using this directory structure so the structure is similar between the Figma file and the Storybook. As I am also giving an overview of the Atomic Design Principles and wanted to give a structure around this. For the "production" component library I worked on, we used a normal file structure `/src/components/button/..` for example. Same for the big component libraries out there ex: [IBM](https://github.com/carbon-design-system/carbon/tree/main/packages/react/src/components), [Fluent UI](https://github.com/microsoft/fluentui/tree/master/packages/react/src/components).
2. Yes I believe it is the way to support full testing on your components. You can have `Xxx.stories.tsx`, `Xxx.spec.ts`, and `Xxx.cy.ts` under each component. Here again, I invite you to check the IBM repo where they are doing just that. [Link](https://github.com/carbon-design-system/carbon/tree/main/packages/react/src/components/Accordion/__tests__).

Let me know how it goes :)

**Comment by zestlee1106** [comment]
1. The project that provides the molcules component uses the same structure as IBM!
(It appears that there are no page components.)
I've always been worried because there are so many components.
Since my project has page and layout, I thought I should divide the directories

2. Looking at the IBM project, it seems to add only when testing is really needed.
[only story](https://github.com/carbon-design-system/carbon/tree/main/packages/react/src/components/Dialog)
[only test](https://github.com/carbon-design-system/carbon/tree/main/packages/react/src/components/CheckboxGroup)
To create a testing-friendly project, the most important point is to use all the tests you need, but to distinguish exactly when you need them.

Thank you for sharing a good example!
